name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
    	  python -m pip install ".[dev]"
    	  python -m pip install build

      - name: Check Ruff version
  	run: |	  
    	  which ruff
    	  ruff --version

      - name: Run Ruff
  	run: |
    	  ruff check .
    	  ruff format --check .

      - name: Static Type Checking (Mypy)
        run: |
          mypy src/

      - name: Run Pytest with Coverage
        run: |
          pytest --cov=src/realta --cov-report=term-missing

      - name: Verify Package Build
        run: |
          python -m build
